language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
services:
  - postgresql

env:
  -DJANGO=2.1.7 DB=posgresql
before_script:
  - psql -c "CREATE DATABASE books;" -U postgres  
script: 
  - 'cd bookstore/'
  - 'python manage.py makemigrations'
  - 'python manage.py migrate'
  - 'coverage run --source="." manage.py test'
  - 'coverage report'
after_success:
  - coveralls
  
