# Generated by Django 2.1.7 on 2019-03-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.IntegerField(),
        ),
    ]
