# Generated by Django 2.1.7 on 2019-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190317_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
